Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Lint/UselessMethodDefinition:
  Enabled: false

Lint/ImplicitStringConcatenation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Lint/EmptyFile:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 25
  Exclude:
    - "db/migrate/*"
