# tutorial: https://qiita.com/Yusuke_Hoirta/items/3a50d066af3bafbb8641
# Youtube: https://www.youtube.com/watch?v=pTFZFxd4hOI

version: "3.8"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    environment:
     - DOCKERIZED=true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  mysql_data:
